import { Stamp } from './Stamp';

export const flowerExtension: Stamp = {
  anchor: { x: 1, y: 1 },
  size: { x: 7, y: 7 },
  roadsCanOverlap: true,

  steps: [
    {
      rcl: 3,
      buildings: {
        extension: [
          { x: 2, y: 1 },
          { x: 3, y: 1 },
          { x: 3, y: 2 },
          { x: 1, y: 2 },
          { x: 1, y: 3 },
          { x: 2, y: 3 },
        ],
        road: [
          { x: 3, y: 3 },
          { x: 2, y: 2 },
          { x: 1, y: 1 },
        ],
      },
    },
    {
      rcl: 4,
      buildings: {
        extension: [
          { x: 2, y: 1 },
          { x: 3, y: 1 },
          { x: 3, y: 2 },
          { x: 4, y: 2 },
          { x: 5, y: 2 },
          { x: 4, y: 3 },
          { x: 1, y: 2 },
          { x: 1, y: 3 },
          { x: 2, y: 3 },
          { x: 2, y: 4 },
          { x: 2, y: 5 },
          { x: 5, y: 4 },
          { x: 4, y: 5 },
          { x: 6, y: 3 },
          { x: 6, y: 4 },
          { x: 6, y: 5 },
          { x: 3, y: 6 },
          { x: 4, y: 6 },
          { x: 5, y: 6 },
          { x: 3, y: 4 },
        ],
        road: [
          { x: 2, y: 6 },
          { x: 3, y: 5 },
          { x: 4, y: 4 },
          { x: 3, y: 3 },
          { x: 2, y: 2 },
          { x: 1, y: 1 },
          { x: 5, y: 3 },
          { x: 6, y: 2 },
          { x: 5, y: 5 },
          { x: 6, y: 6 },
        ],
      },
      operators: [
        {
          coord: { x: 4, y: 4 },
          role: 'flowerFiller',
        },
      ],
    },
    {
      rcl: 5,
      buildings: {
        extension: [
          { x: 2, y: 1 },
          { x: 3, y: 1 },
          { x: 5, y: 1 },
          { x: 6, y: 1 },
          { x: 3, y: 2 },
          { x: 4, y: 2 },
          { x: 5, y: 2 },
          { x: 4, y: 3 },
          { x: 1, y: 2 },
          { x: 1, y: 3 },
          { x: 1, y: 5 },
          { x: 1, y: 6 },
          { x: 2, y: 3 },
          { x: 2, y: 4 },
          { x: 2, y: 5 },
          { x: 5, y: 4 },
          { x: 4, y: 5 },
          { x: 6, y: 3 },
          { x: 6, y: 4 },
          { x: 6, y: 5 },
          { x: 7, y: 2 },
          { x: 7, y: 3 },
          { x: 3, y: 6 },
          { x: 4, y: 6 },
          { x: 5, y: 6 },
          { x: 2, y: 7 },
          { x: 3, y: 7 },
          { x: 1, y: 7 },
          { x: 7, y: 1 },
          { x: 3, y: 4 },
        ],
        road: [
          { x: 2, y: 6 },
          { x: 3, y: 5 },
          { x: 4, y: 4 },
          { x: 3, y: 3 },
          { x: 2, y: 2 },
          { x: 1, y: 1 },
          { x: 5, y: 3 },
          { x: 6, y: 2 },
          { x: 5, y: 5 },
          { x: 6, y: 6 },
        ],
      },

      operators: [
        {
          coord: { x: 4, y: 4 },
          role: 'flowerFiller',
        },
      ],
    },
    {
      rcl: 6,
      buildings: {
        extension: [
          { x: 2, y: 1 },
          { x: 3, y: 1 },
          { x: 5, y: 1 },
          { x: 6, y: 1 },
          { x: 3, y: 2 },
          { x: 4, y: 2 },
          { x: 5, y: 2 },
          { x: 4, y: 3 },
          { x: 1, y: 2 },
          { x: 1, y: 3 },
          { x: 1, y: 5 },
          { x: 1, y: 6 },
          { x: 2, y: 3 },
          { x: 2, y: 4 },
          { x: 2, y: 5 },
          { x: 5, y: 4 },
          { x: 4, y: 5 },
          { x: 6, y: 3 },
          { x: 6, y: 4 },
          { x: 6, y: 5 },
          { x: 7, y: 2 },
          { x: 7, y: 3 },
          { x: 7, y: 5 },
          { x: 7, y: 6 },
          { x: 3, y: 6 },
          { x: 4, y: 6 },
          { x: 5, y: 6 },
          { x: 2, y: 7 },
          { x: 3, y: 7 },
          { x: 5, y: 7 },
          { x: 6, y: 7 },
          { x: 1, y: 7 },
          { x: 7, y: 7 },
          { x: 7, y: 1 },
          { x: 3, y: 4 },
        ],
        road: [
          { x: 2, y: 6 },
          { x: 3, y: 5 },
          { x: 4, y: 4 },
          { x: 3, y: 3 },
          { x: 2, y: 2 },
          { x: 1, y: 1 },
          { x: 5, y: 3 },
          { x: 6, y: 2 },
          { x: 5, y: 5 },
          { x: 6, y: 6 },
        ],
      },
      operators: [
        {
          coord: { x: 4, y: 4 },
          role: 'flowerFiller',
        },
      ],
    },
    {
      rcl: 7,
      buildings: {
        extension: [
          { x: 2, y: 1 },
          { x: 3, y: 1 },
          { x: 5, y: 1 },
          { x: 6, y: 1 },
          { x: 3, y: 2 },
          { x: 4, y: 2 },
          { x: 5, y: 2 },
          { x: 4, y: 3 },
          { x: 1, y: 2 },
          { x: 1, y: 3 },
          { x: 1, y: 5 },
          { x: 1, y: 6 },
          { x: 2, y: 3 },
          { x: 2, y: 4 },
          { x: 2, y: 5 },
          { x: 5, y: 4 },
          { x: 4, y: 5 },
          { x: 6, y: 3 },
          { x: 6, y: 4 },
          { x: 6, y: 5 },
          { x: 7, y: 2 },
          { x: 7, y: 3 },
          { x: 7, y: 5 },
          { x: 7, y: 6 },
          { x: 3, y: 6 },
          { x: 4, y: 6 },
          { x: 5, y: 6 },
          { x: 2, y: 7 },
          { x: 3, y: 7 },
          { x: 5, y: 7 },
          { x: 6, y: 7 },
          { x: 1, y: 7 },
          { x: 7, y: 7 },
          { x: 7, y: 1 },
        ],
        link: [{ x: 3, y: 4 }],
        road: [
          { x: 2, y: 6 },
          { x: 3, y: 5 },
          { x: 4, y: 4 },
          { x: 3, y: 3 },
          { x: 2, y: 2 },
          { x: 1, y: 1 },
          { x: 5, y: 3 },
          { x: 6, y: 2 },
          { x: 5, y: 5 },
          { x: 6, y: 6 },
        ],
      },
      operators: [
        {
          coord: { x: 4, y: 4 },
          role: 'flowerFiller',
        },
      ],
    },
  ],
};
