mods:
    - screepsmod-auth
    - screepsmod-admin-utils
    - screepsmod-mongo
bots:
    simplebot: screepsbot-zeswarm

pinnedPackages:
    ssri: 8.0.1
    cacache: 15.3.0
    passport-steam: 1.0.17
    minipass-fetch: 2.1.2
    express-rate-limit: 6.7.0

launcherOptions:
    # If set, automatically ensures all mods are updated
    autoUpdate: false
    # If set, forward console messages to terminal
    logConsole: true
